[build]
  # Jekyll build command for production
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  # Ruby version
  RUBY_VERSION = "3.2.0"

# Netlify Image Optimization Plugin
[[plugins]]
  package = "@netlify/plugin-image-optim"
  
  [plugins.inputs]
    # Process images in these directories
    inputs = ["assets/images/**/*", "images/**/*", "_site/assets/**/*"]
    
    # Image formats to generate
    formats = ["webp", "avif", "jpeg"]
    
    # Quality settings
    quality = 85
    
    # Responsive image widths
    widths = [320, 640, 1280, 1920]
    
    # Enable progressive JPEG
    progressive = true

# Redirect rules for clean URLs (Jekyll markdown files)
[[redirects]]
  from = "/about/"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/privacy/"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/terms/"
  to = "/terms.html"
  status = 200

# Fallback for all other pages to static HTML
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/resized/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Enable Netlify CMS
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"