[build]
  # Jekyll build command
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

# [핵심 수정] 모든 빌드 컨텍스트에 환경 변수를 명시적으로 설정합니다.
[build.environment]
  RUBY_VERSION = "3.2.0"
  JEKYLL_ENV = "production"

[context.production.environment]
  JEKYLL_ENV = "production"

[context.deploy-preview.environment]
  JEKYLL_ENV = "production"

# --- 아래는 기존 설정을 그대로 유지합니다 ---

# Redirect rules for clean URLs
[[redirects]]
  from = "/about/"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/privacy/"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/terms/"
  to = "/terms.html"
  status = 200

# Fallback for all other pages to static HTML
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/resized/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Enable Netlify CMS
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
